config/routes.rb
Geografispillet::Application.routes.draw do
  resources :authentications
  match '/auth/:provider/callback' => 'authentications#create'
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  resources :user_sessions
  resources :users

  resources :trips
  resources :setups
  resources :countries
  resources :questions

  root :to => "application#index"

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :question, :answer
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :login_required

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(params[:question])
    if @question.save
      redirect_to @question, :notice => "Successfully created question."
    else
      render :action => 'new'
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update_attributes(params[:question])
      redirect_to @question, :notice  => "Successfully updated question."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_url, :notice => "Successfully destroyed question."
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.haml
= form_for @question do |f|
  = f.error_messages
  %p
    = f.label :question
    %br
    = f.text_field :question
  %p
    = f.label :answer
    %br
    = f.text_field :answer
  %p
    = f.submit

app/views/questions/edit.html.haml
- title "Edit Question"

= render 'form'

%p
  = link_to "Show", @question
  |
  = link_to "View All", questions_path

app/views/questions/index.html.haml
%table
  %tr
    %th Question|
    %th Answer
  - for question in @questions
    %tr
      %td= question.question
      %td= question.answer
      %td= link_to 'Show', question
      %td= link_to 'Edit', edit_question_path(question)
      %td= link_to 'Destroy', question, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Question", new_question_path

app/views/questions/new.html.haml
- title "New Question"

= render 'form'

%p= link_to "Back to List", questions_path

app/views/questions/show.html.haml
#main_left_column
  %img#country( src="/images/nokkelskjerm2_uten_landnavn.jpg" ) 

#main_right_column
  %p
    %strong Question:
    = @question.question
  -#%p
  -#  %strong Answer:
  -#  = @question.answer

  - if $show_edit
    %p
      = link_to "Edit", edit_question_path(@question)
      |
      = link_to "Destroy", @question, :confirm => 'Are you sure?', :method => :delete
      |
      = link_to "View All", questions_path

  %table
    %ul
      %li= link_to "Paris", "/questions/2"
      %li= link_to "Berlin", "/questions/1"
      %li= link_to "Oslo", "/questions/1"

- if request.referer.match(/\/questions\/1/)
  - current_user.balance += 100
  - current_user.save