config/routes.rb
Geografispillet::Application.routes.draw do
  resources :authentications
  match '/auth/:provider/callback' => 'authentications#create'
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  resources :user_sessions
  resources :users

  resources :trips
  resources :setups
  resources :countries
  resources :questions

  root :to => "application#index"

end

app/controllers/setups_controller.rb
class SetupsController < ApplicationController
  def index
    @setups = Setup.all
  end

  def show
    @setup = Setup.find(params[:id])
  end

  def new
    @setup = Setup.new
  end

  def create
    @setup = Setup.new(params[:setup])
    if @setup.save
      redirect_to @setup, :notice => "Successfully created setup."
    else
      render :action => 'new'
    end
  end

  def edit
    @setup = Setup.find(params[:id])
  end

  def update
    @setup = Setup.find(params[:id])
    if @setup.update_attributes(params[:setup])
      redirect_to @setup, :notice  => "Successfully updated setup."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @setup = Setup.find(params[:id])
    @setup.destroy
    redirect_to setups_url, :notice => "Successfully destroyed setup."
  end
end

app/helpers/setups_helper.rb
module SetupsHelper
end

app/views/setups/_form.html.haml
= form_for @setup do |f|
  = f.error_messages
  %p
    = f.label :name
    %br
    = f.text_field :name
  %p
    = f.submit

app/views/setups/edit.html.haml
- title "Edit Setup"

= render 'form'

%p
  = link_to "Show", @setup
  |
  = link_to "View All", setups_path

app/views/setups/index.html.haml
- title "Setups"

%table
  %tr
    %th Name
  - for setup in @setups
    %tr
      %td= setup.name
      %td= link_to 'Show', setup
      %td= link_to 'Edit', edit_setup_path(setup)
      %td= link_to 'Destroy', setup, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Setup", new_setup_path

app/views/setups/new.html.haml
- title "New Setup"

= render 'form'

%p= link_to "Back to List", setups_path

app/views/setups/show.html.haml
- title "Setup"

%p
  %strong Name:
  = @setup.name

%p
  = link_to "Edit", edit_setup_path(@setup)
  |
  = link_to "Destroy", @setup, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", setups_path