config/routes.rb
Geografispillet::Application.routes.draw do
  resources :authentications
  match '/auth/:provider/callback' => 'authentications#create'
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  resources :user_sessions
  resources :users

  resources :trips
  resources :setups
  resources :countries
  resources :questions

  root :to => "application#index"

end

app/models/user.rb
class User < ActiveRecord::Base
    acts_as_authentic

    has_many :authentications

    def apply_omniauth(omniauth)
        self.email = omniauth['user_info']['email']

        # Update user info fetching from social network
        case omniauth['provider']
        when 'facebook'
            # fetch extra user info from facebook
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required, :except => [:new, :create]

  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /userss/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Thank you for signing up! You are now logged in."
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Your profile has been updated."
    else
      render :action => 'edit'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user do |f|
  = f.error_messages
  %p
    = f.label :username
    %br
    = f.text_field :username
  %p
    = f.label :email, "Epost"
    %br
    = f.text_field :email
  %p
    = f.label :password
    %br
    = f.password_field :password
  %p
    = f.label :password_confirmation, "Bekreft"
    %br
    = f.password_field :password_confirmation
  %p
    = f.submit (@user.new_record? ? "Registrer" : "Oppdater")

app/views/users/edit.html.haml
- title "Endre profil"

= render 'form'

app/views/users/index.html.haml
%h1 Lister opp brukere

%table
  %tr
    %th Brukernavn
    %th Epost

  - @users.each do |user|
    %tr
      %td= user.username
      %td= user.email
      %td= link_to 'Vis', user
      %td= link_to 'Endre', edit_user_path(user)
      %td= link_to 'Slett', user, :confirm => 'Er du sikker?', :method => :delete

%br
= link_to 'Autentiseringer', authentications_path
= link_to 'Ny bruker', new_user_path

app/views/users/new.html.haml
- title "Registrer"

%p== Har du allerede konto? #{link_to "Logg inn", login_path}.

= render 'form'

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Brukernavn:
  = @user.username
%p
  %b Epost:
  = @user.email

= link_to 'Endre', edit_user_path(@user)
\|
= link_to 'Tilbake', users_path