config/routes.rb
Geografispillet::Application.routes.draw do
  resources :authentications
  match '/auth/:provider/callback' => 'authentications#create'
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  resources :user_sessions
  resources :users

  resources :trips
  resources :setups
  resources :countries
  resources :questions

  root :to => "application#index"

end

app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :name, :population, :area, :currency, :capital
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_filter :login_required

  def index
    @countries = Country.all
  end

  def show
    @country = Country.find(params[:id])
  end

  def new
    @country = Country.new
  end

  def create
    @country = Country.new(params[:country])
    if @country.save
      redirect_to @country, :notice => "Successfully created country."
    else
      render :action => 'new'
    end
  end

  def edit
    @country = Country.find(params[:id])
  end

  def update
    @country = Country.find(params[:id])
    if @country.update_attributes(params[:country])
      redirect_to @country, :notice  => "Successfully updated country."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @country = Country.find(params[:id])
    @country.destroy
    redirect_to countries_url, :notice => "Successfully destroyed country."
  end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_form.html.haml
= form_for @country do |f|
  = f.error_messages
  %p
    = f.label :name
    %br
    = f.text_field :name
  %p
    = f.label :population
    %br
    = f.text_field :population
  %p
    = f.label :area
    %br
    = f.text_field :area
  %p
    = f.label :currency
    %br
    = f.text_field :currency
  %p
    = f.label :capital
    %br
    = f.text_field :capital
  %p
    = f.submit

app/views/countries/edit.html.haml
- title "Edit Country"

= render 'form'

%p
  = link_to "Show", @country
  |
  = link_to "View All", countries_path

app/views/countries/index.html.haml
- title "Countries"

%table
  %tr
    %th Name|
    %th Population|
    %th Area|
    %th Currency|
    %th Capital
  - for country in @countries
    %tr
      %td= country.name
      %td= country.population
      %td= country.area
      %td= country.currency
      %td= country.capital
      %td= link_to 'Show', country
      %td= link_to 'Edit', edit_country_path(country)
      %td= link_to 'Destroy', country, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Country", new_country_path

app/views/countries/new.html.haml
- title "New Country"

= render 'form'

%p= link_to "Back to List", countries_path

app/views/countries/show.html.haml
%img#background( src="/images/nokkelskjerm2_uten_landnavn.jpg" )

  #imagetext
    - 8.times do
      %br

    - if $show_edit
      %p
        = link_to "Edit", edit_country_path(@country)
        |
        = link_to "Destroy", @country, :confirm => 'Are you sure?', :method => :delete
        |
        = link_to "View All", countries_path

    %br
    %p#imagetext_bg
      = link_to "Tjen penger - svar på spørsmål!", "/questions/1"